### 노드 생성
POST http://localhost:8080/nodes
Content-Type: application/json

{
  "id": 3,
  "name": "aiden3"
}

### 노드 전체 조회
GET http://localhost:8080/nodes

### 노드 상세 조회
GET http://localhost:8080/nodes/1

### 노드 제거
DELETE http://localhost:8080/nodes/1

### 관계 생성
POST http://localhost:8080/nodes/relations/1
Content-Type: application/json

{
  "targetNodeIds": [
    2,
    3
  ]
}