### 유저 정보 추가
POST http://localhost:8080/users
Content-Type: application/json

{
  "userId": 10,
  "name": "10인근",
  "skillIds": [
    1,
    3,
    5,
    7,
    9
  ]
}

### 유저 스킬 정보 갱신
PUT http://localhost:8080/users/skills
Content-Type: application/json

{
  "userId": 10,
  "skillIds": [
    2,
    4
  ]
}

### 특정 유저와 유사한 스킬을 가진 유저 목록 조회
GET http://localhost:8080/users/1/skill-similarity?limit=5